language: go

go:
  - 1.5
  - tip

install:
  - go get -v ./...
  - go get -v github.com/aws/aws-sdk-go/...
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2 --nodes=2
